package stripehooks

type EventType string

// Event types available.
const (
	AccoutnApplicationAuthorized                EventType = "account.application.authorized"                  // Occurs whenever a user authorizes an application. Sent to the related application only.
	AccountApplicationDeauthorized              EventType = "account.application.deauthorized"                // Occurs whenever a user deauthorizes an application. Sent to the related application only.
	AccountExternalAccountCreated               EventType = "account.external_account.created"                // Occurs whenever an external account is created.
	AccountExternalAccountUpdated               EventType = "account.external_account.updated"                // Occurs whenever an external account is updated.
	AccountExternalAccountDeleted               EventType = "account.external_account.deleted"                // Occurs whenever an external account is deleted.
	AccountUpdated                              EventType = "account.updated"                                 // Occurs whenever an account status or property has changed.
	ApplicationFeeCreated                       EventType = "application_fee.created"                         // Occurs whenever an application fee is created on a charge.
	ApplicationFeeRefundUpdated                 EventType = "application_fee.refund.updated"                  // Occurs whenever an application fee refund is updated.
	ApplicationFeeRefunded                      EventType = "application_fee.refunded"                        // Occurs whenever an application fee is refunded, whether from refunding a charge or from refunding the application fee directly, including partial refunds.
	BalanceAvailable                            EventType = "balance.available"                               // Occurs whenever your Stripe balance has been updated (e.g. when a charge collected is available to be paid out). By default, Stripe will automatically transfer any funds in your balance to your bank account on a daily basis.
	BillingPortalConfigurationCreated           EventType = "billing_portal.configuration.created"            // Occurs whenever a billing portal configuration is created.
	BillingPortalConfigurationUpdated           EventType = "billing_portal.configuration.updated"            // Occurs whenever a billing portal configuration is updated.
	BillingPortalSessionCreated                 EventType = "billing_portal.session.created"                  // Occurs whenever a billing portal session is created.
	CapabilityUpdated                           EventType = "capability.updated"                              // Occurs whenever a capability has new requirements or a new status.
	CashBalanceFundsAvailable                   EventType = "cash_balance.funds_available"                    // Occurs whenever funds are received into your Stripe account.
	ChargeCaptured                              EventType = "charge.captured"                                 // Occurs whenever a previously uncaptured charge is captured.
	ChargeDisputeClosed                         EventType = "charge.dispute.closed"                           // Occurs when the dispute is closed and the dispute status changes to charge_refunded, lost, warning_closed, or won.
	ChargeDisputeCreated                        EventType = "charge.dispute.created"                          // Occurs whenever a customer disputes a charge with their bank (chargeback).
	ChargeDisputeFundsReinstated                EventType = "charge.dispute.funds_reinstated"                 // Occurs when funds are reinstated to your account after a dispute is won.
	ChargeDisputeFundsWithdrawn                 EventType = "charge.dispute.funds_withdrawn"                  // Occurs when funds are removed from your account due to a dispute.
	ChargeDisputeUpdated                        EventType = "charge.dispute.updated"                          // Occurs when the dispute is updated (usually with evidence).
	ChargeExpired                               EventType = "charge.expired"                                  // Occurs whenever a failed charge attempt succeeds in the next retry attempt.
	ChargeFailed                                EventType = "charge.failed"                                   // Occurs whenever a failed charge attempt occurs.
	ChargePending                               EventType = "charge.pending"                                  // Occurs whenever a pending charge is created.
	ChargeRefundUpdated                         EventType = "charge.refund.updated"                           // Occurs whenever a refund is updated, on selected payment methods.
	ChargeRefunded                              EventType = "charge.refunded"                                 // Occurs whenever a charge is refunded, including partial refunds.
	ChargeSucceeded                             EventType = "charge.succeeded"                                // Occurs whenever a new charge is created and is successful.
	ChargeUpdated                               EventType = "charge.updated"                                  // Occurs whenever a charge description or metadata is updated.
	CheckoutSessionAsyncPaymentFailed           EventType = "checkout.session.async_payment_failed"           // Occurs whenever an asynchronous payment attempt fails.
	CheckoutSessionAsyncPaymentSucceeded        EventType = "checkout.session.async_payment_succeeded"        // Occurs whenever an asynchronous payment attempt succeeds.
	ChekoutSessionCompleted                     EventType = "checkout.session.completed"                      // Occurs whenever a checkout session has been successfully completed.
	CheckoutSessionExpired                      EventType = "checkout.session.expired"                        // Occurs whenever a checkout session has expired.
	CouponCreated                               EventType = "coupon.created"                                  // Occurs whenever a coupon is created.
	CouponDeleted                               EventType = "coupon.deleted"                                  // Occurs whenever a coupon is deleted.
	CouponUpdated                               EventType = "coupon.updated"                                  // Occurs whenever a coupon is updated.
	CreditNoteCreated                           EventType = "credit_note.created"                             // Occurs whenever a credit note is created.
	CreditNoteUpdated                           EventType = "credit_note.updated"                             // Occurs whenever a credit note is updated.
	CreditNoteVoided                            EventType = "credit_note.voided"                              // Occurs whenever a credit note is voided.
	CustomerCashBalanceTransactionCreated       EventType = "customer.cash_balance_transaction.created"       // Occurs whenever a customer balance transaction is created.
	CustomerCreated                             EventType = "customer.created"                                // Occurs whenever a new customer is created.
	CustomerDeleted                             EventType = "customer.deleted"                                // Occurs whenever a customer is deleted.
	CustomerDiscountCreated                     EventType = "customer.discount.created"                       // Occurs whenever a coupon is attached to a customer.
	CustomerDiscountDeleted                     EventType = "customer.discount.deleted"                       // Occurs whenever a customer's discount is removed.
	CustomerDiscountUpdated                     EventType = "customer.discount.updated"                       // Occurs whenever a customer is switched from one coupon to another.
	CustomerSourceCreated                       EventType = "customer.source.created"                         // Occurs whenever a new source is created for the customer.
	CustomerSourceDeleted                       EventType = "customer.source.deleted"                         // Occurs whenever a source is removed from a customer.
	CustomerSourceExpiring                      EventType = "customer.source.expiring"                        // Occurs whenever a card or source will expire at the end of the month.
	CustomerSourceUpdated                       EventType = "customer.source.updated"                         // Occurs whenever a source's details are changed.
	CustomerSubscriptionCreated                 EventType = "customer.subscription.created"                   // Occurs whenever a customer with no subscription is signed up for a plan.
	CustomerSubscriptionDeleted                 EventType = "customer.subscription.deleted"                   // Occurs whenever a customer ends their subscription.
	CusteromSubscriptionPaused                  EventType = "customer.subscription.paused"                    // Occurs whenever a customer pauses their subscription.
	CustomerSubscriptionPendingUpdateApplied    EventType = "customer.subscription.pending_update_applied"    // Occurs whenever a customer's subscription's pending update is applied, and the subscription is updated.
	CustomerSubscriptionPendingUpdateExpired    EventType = "customer.subscription.pending_update_expired"    // Occurs whenever a customer's subscription's pending update expires before the related invoice is paid.
	CustomerSubscriptionResumed                 EventType = "customer.subscription.resumed"                   // Occurs whenever a customer resumes their subscription.
	CustomerSubscriptionTrialWillEnd            EventType = "customer.subscription.trial_will_end"            // Occurs three days before the trial period of a subscription is scheduled to end.
	CustomerSubscriptionUpdated                 EventType = "customer.subscription.updated"                   // Occurs whenever a subscription changes. Examples would include switching from one plan to another, or switching status from trial to active.
	CustomerTaxIdCreated                        EventType = "customer.tax_id.created"                         // Occurs whenever a tax ID is created for a customer.
	CustomerTaxIdDeleted                        EventType = "customer.tax_id.deleted"                         // Occurs whenever a tax ID is deleted from a customer.
	CustomerTaxIdUpdated                        EventType = "customer.tax_id.updated"                         // Occurs whenever a tax ID is updated on a customer.
	CustomerUpdated                             EventType = "customer.updated"                                // Occurs whenever any property of a customer changes.
	FileCreated                                 EventType = "file.created"                                    // Occurs whenever a new file is created.
	FinancialConnectionsAccountCreated          EventType = "financial_connections.account.created"           // Occurs whenever a new account is created in a financial service.
	FinancialConnectionsAccountDeactivated      EventType = "financial_connections.account.deactivated"       // Occurs whenever an account is deactivated in a financial service.
	FinancialConnectionsAccountDisconnected     EventType = "financial_connections.account.disconnected"      // Occurs whenever an account is disconnected from a financial service.
	FinancialConnectionsAccountReactivated      EventType = "financial_connections.account.reactivated"       // Occurs whenever an account is reactivated in a financial service.
	FinancialConnectionsAccountRefreshedBalance EventType = "financial_connections.account.refreshed_balance" // Occurs whenever an account's balance is refreshed in a financial service.
	IdentityVerificationSessionCanceled         EventType = "identity.verification_session.canceled"          // Occurs whenever an identity verification session is canceled.
	IdentityVerificationSessionCreated          EventType = "identity.verification_session.created"           // Occurs whenever an identity verification session is created.
	IdentityVerificationSesssionProcessing      EventType = "identity.verification_session.processing"        // Occurs whenever an identity verification session is processing.
	IdentityVerificationSessionRedacted         EventType = "identity.verification_session.redacted"          // Occurs whenever an identity verification session is redacted.
	IdentityVerificationSessionRequiresInput    EventType = "identity.verification_session.requires_input"    // Occurs whenever an identity verification session requires additional input.
	IdentityVerificationSessionVerified         EventType = "identity.verification_session.verified"          // Occurs whenever an identity verification session is verified.
	InvoiceCreated                              EventType = "invoice.created"                                 // Occurs whenever a new invoice is created. If you are using webhooks, Stripe will wait one hour after they have all succeeded to attempt to pay the invoice; the only exception here is on the first invoice, which gets created and paid immediately when you subscribe a customer to a plan. If your webhooks do not all respond successfully, Stripe will continue retrying the webhooks every hour and will not attempt to pay the invoice. After 3 days, Stripe will attempt to pay the invoice regardless of whether or not your webhooks have succeeded. See  how to respond to a webhook.
	InvoiceDeleted                              EventType = "invoice.deleted"                                 // Occurs whenever an invoice is deleted.
	InvoiceFinalizationFailed                   EventType = "invoice.finalization_failed"                     // Occurs whenever an invoice finalization attempt fails.
	InvoiceMarkedUncollectible                  EventType = "invoice.marked_uncollectible"                    // Occurs whenever an invoice is marked uncollectible.
	InvoicePayed                                EventType = "invoice.paid"                                    // Occurs whenever an invoice payment attempt succeeds or the invoice is marked as paid out-of-band.
	InvoicePaymentActionRequired                EventType = "invoice.payment_action_required"                 // Occurs whenever an invoice payment attempt requires further user action to complete.
	InvoicePaymentFailed                        EventType = "invoice.payment_failed"                          // Occurs whenever an invoice attempts to be paid, and the payment fails. This can occur either due to a declined payment, or because the customer has no active card. A particular case of note is that if a customer with no active card reaches the end of its free trial, an invoice.payment_failed notification will occur.
	InvoicePaymentSucceeded                     EventType = "invoice.payment_succeeded"                       // Occurs whenever an invoice attempts to be paid, and the payment succeeds.
	InvoiceSent                                 EventType = "invoice.sent"                                    // Occurs whenever an invoice email is sent out.
	InvoiceUpcoming                             EventType = "invoice.upcoming"                                // Occurs X number of days before a subscription is scheduled to create an invoice that is automatically charged—where X is determined by your subscriptions settings. Note: The received Invoice object will not have an invoice ID.
	InvoiceUpdated                              EventType = "invoice.updated"                                 // Occurs whenever an invoice changes (for example, the amount could change).
	InvoiceitemCreated                          EventType = "invoiceitem.created"                             // Occurs whenever an invoice item is created.
	InvoiceitemDeleted                          EventType = "invoiceitem.deleted"                             // Occurs whenever an invoice item is deleted.
	InvoiceitemUpdated                          EventType = "invoiceitem.updated"                             // Occurs whenever an invoice item is updated.
	IssuingAuthorizationCreated                 EventType = "issuing_authorization.created"                   // Occurs whenever an issuing authorization is created.
	IssuingAuthorizationRequest                 EventType = "issuing_authorization.request"                   // Occurs whenever an issuing authorization request is created.
	IssuingAuthorizationUpdated                 EventType = "issuing_authorization.updated"                   // Occurs whenever an issuing authorization is updated.
	IssuingCardCreated                          EventType = "issuing_card.created"                            // Occurs whenever an issuing card is created.
	IssuingCardUpdated                          EventType = "issuing_card.updated"                            // Occurs whenever an issuing card is updated.
	IssuingCardholderCreated                    EventType = "issuing_cardholder.created"                      // Occurs whenever an issuing cardholder is created.
	IssuingCardholderUpdated                    EventType = "issuing_cardholder.updated"                      // Occurs whenever an issuing cardholder is updated.
	IssuingDisputeClosed                        EventType = "issuing_dispute.closed"                          // Occurs whenever an issuing dispute is closed.
	IssuingDisputeCreated                       EventType = "issuing_dispute.created"                         // Occurs whenever an issuing dispute is created.
	IssuingDisputeFundsReinstated               EventType = "issuing_dispute.funds_reinstated"                // Occurs whenever funds are reinstated to an issuing dispute.
	IssuingDisputeSubmitted                     EventType = "issuing_dispute.submitted"                       // Occurs whenever an issuing dispute is submitted.
	IssuingDisputeUpdated                       EventType = "issuing_dispute.updated"                         // Occurs whenever an issuing dispute is updated.
	IssuingTransactionCreated                   EventType = "issuing_transaction.created"                     // Occurs whenever an issuing transaction is created.
	IssuingTransactionUpdated                   EventType = "issuing_transaction.updated"                     // Occurs whenever an issuing transaction is updated.
	MandateUpdated                              EventType = "mandate.updated"                                 // Occurs whenever a mandate is updated.
	OrderCreated                                EventType = "order.created"                                   // Occurs whenever an order is created.
	PaymentIntentAmountCapturableUpdated        EventType = "payment_intent.amount_capturable_updated"        // Occurs whenever the amount_capturable of a PaymentIntent changes.
	PaymentIntentCanceled                       EventType = "payment_intent.canceled"                         // Occurs whenever a PaymentIntent is canceled.
	PaymentIntentCreated                        EventType = "payment_intent.created"                          // Occurs whenever a PaymentIntent is created.
	PaymentIntentPartillyFunded                 EventType = "payment_intent.partially_funded"                 // Occurs whenever a PaymentIntent has funds partially collected.
	PaymentIntentPaymentFailed                  EventType = "payment_intent.payment_failed"                   // Occurs whenever a PaymentIntent has a payment attempt attempt fail.
	PaymentIntentProcessing                     EventType = "payment_intent.processing"                       // Occurs whenever a PaymentIntent has a payment attempt succeed.
	PaymentIntentRequiresAction                 EventType = "payment_intent.requires_action"                  // Occurs whenever a PaymentIntent has a Source that requires a customer action.
	PaymentIntentSucceeded                      EventType = "payment_intent.succeeded"                        // Occurs whenever a PaymentIntent has a payment attempt succeed.
	PayoutLinkCreated                           EventType = "payout_link.created"                             // Occurs whenever a payout link is created.
	PayoutLinkUpdated                           EventType = "payout_link.updated"                             // Occurs whenever a payout link is updated.
	PaymentMethodAttached                       EventType = "payment_method.attached"                         // Occurs whenever a PaymentMethod is attached to a Customer.
	PaymentMethodCardAutomaticallyUpdated       EventType = "payment_method.card_automatically_updated"       // Occurs whenever a card PaymentMethod's details are automatically updated by the network.
	PaymentMethodDetached                       EventType = "payment_method.detached"                         // Occurs whenever a PaymentMethod is detached from a Customer.
	PaymentMethodUpdated                        EventType = "payment_method.updated"                          // Occurs whenever a PaymentMethod is updated via the API.
	PayoutCanceled                              EventType = "payout.canceled"                                 // Occurs whenever a payout is canceled.
	PayoutCreated                               EventType = "payout.created"                                  // Occurs whenever a payout is created.
	PayoutFailed                                EventType = "payout.failed"                                   // Occurs whenever a payout attempt fails.
	PayoutPaid                                  EventType = "payout.paid"                                     // Occurs whenever a payout is expected to be available in the destination account. If the payout fails, a payout.failed notification is also sent, at a later time.
	PayoutReconciliationCompleted               EventType = "payout.reconciliation.completed"                 // Occurs whenever a payout is reconciled with Stripe.
	PayoutUpdated                               EventType = "payout.updated"                                  // Occurs whenever a payout's metadata is updated.
	PersonCreated                               EventType = "person.created"                                  // Occurs whenever a person is created.
	PersonDeleted                               EventType = "person.deleted"                                  // Occurs whenever a person is deleted.
	PersonUpdated                               EventType = "person.updated"                                  // Occurs whenever a person is updated.
	PlanCreated                                 EventType = "plan.created"                                    // Occurs whenever a plan is created.
	PlanDeleted                                 EventType = "plan.deleted"                                    // Occurs whenever a plan is deleted.
	PlanUpdated                                 EventType = "plan.updated"                                    // Occurs whenever a plan is updated.
	PriceCreated                                EventType = "price.created"                                   // Occurs whenever a price is created.
	PriceDeleted                                EventType = "price.deleted"                                   // Occurs whenever a price is deleted.
	PriceUpdated                                EventType = "price.updated"                                   // Occurs whenever a price is updated.
	ProductCreated                              EventType = "product.created"                                 // Occurs whenever a product is created.
	ProductDeleted                              EventType = "product.deleted"                                 // Occurs whenever a product is deleted.
	ProductUpdated                              EventType = "product.updated"                                 // Occurs whenever a product is updated.
	PromotionCodeCreated                        EventType = "promotion_code.created"                          // Occurs whenever a promotion code is created.
	PromotionCodeUpdated                        EventType = "promotion_code.updated"                          // Occurs whenever a promotion code is updated.
	QuoteAccepted                               EventType = "quote.accepted"                                  // Occurs whenever a quote is accepted.
	QuoteCanceled                               EventType = "quote.canceled"                                  // Occurs whenever a quote is canceled.
	QuoteCreated                                EventType = "quote.created"                                   // Occurs whenever a quote is created.
	QuoteFinalized                              EventType = "quote.finalized"                                 // Occurs whenever a quote is finalized.
	RadarEarlyFraudWarningCreated               EventType = "radar.early_fraud_warning.created"               // Occurs whenever a new early fraud warning is created.
	RadarEarlyFraudWarningUpdated               EventType = "radar.early_fraud_warning.updated"               // Occurs whenever an early fraud warning is updated.
	RecipientCreated                            EventType = "recipient.created"                               // Occurs whenever a recipient is created.
	RecipientDeleted                            EventType = "recipient.deleted"                               // Occurs whenever a recipient is deleted.
	RecipientUpdated                            EventType = "recipient.updated"                               // Occurs whenever a recipient is updated.
	RefundCreated                               EventType = "refund.created"                                  // Occurs whenever a refund is created.
	RefundUpdated                               EventType = "refund.updated"                                  // Occurs whenever a refund is updated.
	ReportingReportRunFailed                    EventType = "reporting.report_run.failed"                     // Occurs whenever a report run fails.
	ReportingReportRunSucceeded                 EventType = "reporting.report_run.succeeded"                  // Occurs whenever a report run succeeds.
	ReportingReportTypeUpdated                  EventType = "reporting.report_type.updated"                   // Occurs whenever a report type is updated.
	ReviewClosed                                EventType = "review.closed"                                   // Occurs whenever a review is closed.
	ReviewOpened                                EventType = "review.opened"                                   // Occurs whenever a review is opened.
	SetupIntentCanceled                         EventType = "setup_intent.canceled"                           // Occurs whenever a SetupIntent is canceled.
	SetupIntentCreated                          EventType = "setup_intent.created"                            // Occurs whenever a SetupIntent is created.
	SetupIntentRequiresAction                   EventType = "setup_intent.requires_action"                    // Occurs whenever a SetupIntent has a status of requires_action.
	SetupIntentSetupFailed                      EventType = "setup_intent.setup_failed"                       // Occurs whenever a SetupIntent has a status of setup_failed.
	SetupIntentSucceeded                        EventType = "setup_intent.succeeded"                          // Occurs whenever a SetupIntent has a status of succeeded.
	SigmaScheduledQueryRunCreated               EventType = "sigma.scheduled_query_run.created"               // Occurs whenever a new scheduled query run finishes successfully.
	SkuCreated                                  EventType = "sku.created"                                     // Occurs whenever a SKU is created.
	SkuDeleted                                  EventType = "sku.deleted"                                     // Occurs whenever a SKU is deleted.
	SkuUpdated                                  EventType = "sku.updated"                                     // Occurs whenever a SKU is updated.
	SourceCanceled                              EventType = "source.canceled"                                 // Occurs whenever a source is canceled.
	SourceChargeable                            EventType = "source.chargeable"                               // Occurs whenever a source transitions to chargeable.
	SourceFailed                                EventType = "source.failed"                                   // Occurs whenever a source fails.
	SourceMandateNotification                   EventType = "source.mandate_notification"                     // Occurs whenever a source mandate notification method is set to manual.
	SourceRefundAttributesRequired              EventType = "source.refund_attributes_required"               // Occurs whenever a source's refund attributes are required.
	SourceTransactionCreated                    EventType = "source.transaction.created"                      // Occurs whenever a source transaction is created.
	SourceTransactionUpdated                    EventType = "source.transaction.updated"                      // Occurs whenever a source transaction is updated.
	SubscriptionScheduleAborted                 EventType = "subscription_schedule.aborted"                   // Occurs whenever a subscription schedule is canceled due to the underlying subscription being canceled because of delinquency.
	SubscriptionScheduleCanceled                EventType = "subscription_schedule.canceled"                  // Occurs whenever a subscription schedule is canceled.
	SubscriptionScheduleCompleted               EventType = "subscription_schedule.completed"                 // Occurs whenever a subscription schedule transitions to a completed state.
	SubscriptionScheduleCreated                 EventType = "subscription_schedule.created"                   // Occurs whenever a new subscription schedule is created.
	SubscriptionScheduleExpiring                EventType = "subscription_schedule.expiring"                  // Occurs whenever a subscription schedule is expiring.
	SubscriptionScheduleReleased                EventType = "subscription_schedule.released"                  // Occurs whenever a new subscription schedule is released.
	SubscriptionScheduleUpdated                 EventType = "subscription_schedule.updated"                   // Occurs whenever a subscription schedule is updated.
	TaxRateCreated                              EventType = "tax_rate.created"                                // Occurs whenever a tax rate is created.
	TaxRateUpdated                              EventType = "tax_rate.updated"                                // Occurs whenever a tax rate is updated.
	TerminalReaderActionFailed                  EventType = "terminal.reader_action_failed"                   // Occurs whenever a reader's connection status has changed.
	TerminalReaderActionSucceeded               EventType = "terminal.reader_action_succeeded"                // Occurs whenever a reader's connection status has changed.
	TopupCanceled                               EventType = "topup.canceled"                                  // Occurs whenever a top-up is canceled.
	TopupCreated                                EventType = "topup.created"                                   // Occurs whenever a top-up is created.
	TopupFailed                                 EventType = "topup.failed"                                    // Occurs whenever a top-up fails.
	TopupReversed                               EventType = "topup.reversed"                                  // Occurs whenever a top-up is reversed.
	TopupSucceeded                              EventType = "topup.succeeded"                                 // Occurs whenever a top-up succeeds.
	TransferCreated                             EventType = "transfer.created"                                // Occurs whenever a new transfer is created.
	TransferReversed                            EventType = "transfer.reversed"                               // Occurs whenever a transfer is reversed, including partial reversals.
	TransferUpdated                             EventType = "transfer.updated"                                // Occurs whenever the description or metadata of a transfer is updated.
)
